
package edu.wpi.first.wpilibj.templates;

// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.templates.commands.AutonomousCommand;
import edu.wpi.first.wpilibj.templates.commands.Compressoroff;
import edu.wpi.first.wpilibj.templates.commands.Compressorstart;
import edu.wpi.first.wpilibj.templates.commands.DriveSetpiont;
import edu.wpi.first.wpilibj.templates.commands.ExtendKicker;
import edu.wpi.first.wpilibj.templates.commands.Extenddumper;
import edu.wpi.first.wpilibj.templates.commands.ResetEncoders;
import edu.wpi.first.wpilibj.templates.commands.RetractDumper;
import edu.wpi.first.wpilibj.templates.commands.RetractKicker;
import edu.wpi.first.wpilibj.templates.commands.TankDrive;
/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    
    // Another type of button you can create is a DigitalIOButton, which is
    // a button or switch hooked up to the cypress module. These are useful if
    // you want to build a customized operator interface.
    // Button button = new DigitalIOButton(1);
    
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick leftStick;
    public Joystick rightStick;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        rightStick = new Joystick(2);
        
        leftStick = new Joystick(1);
        
	    
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        
        //Solenoids
        SmartDashboard.putData("ExtendDumper: ", new Extenddumper());
        SmartDashboard.putData("RetractDumper: ", new RetractDumper());
        SmartDashboard.putData("ExtendKicker: ", new ExtendKicker());
        SmartDashboard.putData("RetractKicker: ", new RetractKicker());
        
        //Compresssor
        SmartDashboard.putData("CompressorOn: ", new Compressorstart());
        SmartDashboard.putData("ComressorOff: ", new Compressoroff());
        
      
        
        //Encoders
        SmartDashboard.putData("ResetEncoders: ", new ResetEncoders());
        
        //Commands
        SmartDashboard.putData("TankDrive", new TankDrive());
        SmartDashboard.putData("DriveSetPiont", new DriveSetpiont());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public double getLeftStick() {
        return -leftStick.getY();
    }
    public double getRightStick() {
        return -rightStick.getY();
    }
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}
